name: Telegram News Bot

on:
  schedule:
    - cron: '30 2 * * *'
  workflow_dispatch:

jobs:
  send-news:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install feedparser

      - name: Create Environment File
        run: |
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> newsbot.env
          echo "CHAT_ID=${{ secrets.CHAT_ID }}" >> newsbot.env

      - name: Run Bot
        run: |
          python news_bot.py
